server:
  port : 8701
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8700/eureka
      instance:
      preferIpAddress: true
spring:
   application:
      name: student-service

